version: '3'
services:
  data-base:
    image: mysql:8.0
    container_name: string_manipulation
    volumes:
      - ./data-base:/var/lib/mysql
    ports:
      - 33060:3306
    restart: on-failure
    environment:
      - MYSQL_ROOT_PASSWORD=password