# version: '3'
# services:
#   frontend:
#     build: frontend/    # Especificamos o contexto, ou seja, a pasta onde está o Dockerfile.
#     restart: on-failure
#     ports:
#       - 3000:3000
#     depends_on:
#       - backend
#   backend:
#     build: backend/     # Mesmo caso aqui.
#     restart: on-failure
#     ports:
#       - 3001:3001
#     environment:
#       - DB_HOST=database
#     depends_on:
#       - database
#   database:
#     image: betrybe/docker-compose-example-database:v1    # Especificamos a Imagem Docker diretamente.
#     restart: on-failure

version: "3"
services:
  frontend:
    build: frontend/
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - rede-virtual-1
  backend:
    build: backend/
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1
    restart: always
    volumes:
      - dados-do-banco:/data/db
    networks:
      - rede-virtual-2

volumes:
  dados-do-banco:

networks:
  rede-virtual-1:
  rede-virtual-2: