version: '3'
services:
  data-base:
    image: mysql:8.0
    restart: on-failure
    volumes:
      - ./data-base:/var/lib/mysql
    ports:
      - 33060:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dbbooks